# Generated by Django 5.2.4 on 2025-08-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_login_register_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Respository",
            new_name="Resume",
        ),
    ]
