# Generated by Django 5.2.4 on 2025-08-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_login_password_alter_register_password"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Login",
        ),
    ]
