# Generated by Django 5.2.4 on 2025-08-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_delete_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="role",
            field=models.CharField(default="user", max_length=20),
        ),
    ]
