# Generated by Django 3.2.12 on 2025-10-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
