# Generated by Django 5.2.4 on 2025-08-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_respository_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="register",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
