# Generated by Django 5.2.3 on 2026-06-10 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAIQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.IntegerField(default=50)),
                ('monthly_limit', models.IntegerField(default=1000)),
                ('daily_usage', models.IntegerField(default=0)),
                ('monthly_usage', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quota', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('duration', models.FloatField(help_text='Request duration in seconds')),
                ('status_code', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='api_aiusage_user_id_78c5cb_idx'), models.Index(fields=['endpoint', 'created_at'], name='api_aiusage_endpoin_7c8a52_idx'), models.Index(fields=['ip_address', 'created_at'], name='api_aiusage_ip_addr_e5db58_idx')],
            },
        ),
    ]
