version: "3"

services:
    server:
      build: 
          context: .
      ports:
        - "8000:8000" 
      volumes:
        - .:/app
      command: >
        sh -c "python manage.py runserver 0.0.0.0:8000"

# docker-compose run server sh -c "django-admin startproject newproject ."
